# Generated by Django 5.2.4 on 2025-07-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(editable=False, unique=True)),
                ('texto', models.TextField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscanearQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_qr.qr')),
            ],
        ),
        migrations.AddField(
            model_name='qr',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_qr.tipoqr'),
        ),
    ]
